In [11]:
!pwd
#%cd Trajectory


/Users/obara/Library/CloudStorage/OneDrive-東京理科大学/2022研究室/卒論/コード関係


In [13]:
%cd ..
import argparse
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from PIL import Image

from utils.parser import *

/Users/obara/Library/CloudStorage/OneDrive-東京理科大学/2022研究室/卒論/コード関係/Trajectory_local_obara


In [14]:
text = "texts/1012_study.txt"
df = parser_byte(text)
#df = centerize(df)
df


frame   ID        x        y      w      h
0          1    1  1218.38   725.36  32.39  54.36
1          2    1  1217.92   725.66  32.23  53.96
2          3    1  1217.80   728.32  31.11  51.80
3          4    1  1217.19   729.12  30.92  51.16
4          5    1  1217.17   730.31  30.56  50.02
...      ...  ...      ...      ...    ...    ...
87226  12743  403  1172.01   934.92  30.56  54.96
87227  12743  404  1203.36   945.44  43.58  68.10
87228  12743  405  1204.67  1020.77  30.50  55.69
87229  12743  406  1274.44  1029.32  36.77  61.23
87230  12743  407  1240.11  1031.58  33.43  68.43

[87231 rows x 6 columns]

In [6]:
df.groupby(['ID'])
df

frame   ID        x        y      w      h
0          1    1  1218.38   725.36  32.39  54.36
1          2    1  1217.92   725.66  32.23  53.96
2          3    1  1217.80   728.32  31.11  51.80
3          4    1  1217.19   729.12  30.92  51.16
4          5    1  1217.17   730.31  30.56  50.02
...      ...  ...      ...      ...    ...    ...
87226  12743  403  1172.01   934.92  30.56  54.96
87227  12743  404  1203.36   945.44  43.58  68.10
87228  12743  405  1204.67  1020.77  30.50  55.69
87229  12743  406  1274.44  1029.32  36.77  61.23
87230  12743  407  1240.11  1031.58  33.43  68.43

[87231 rows x 6 columns]

In [13]:
df2 = df
df2= df2.query(' 1100< x < 1500 & 900 <y<910')
#df2.groupby(["ID"])
 #pd.get_option("display.max_columns")

#最大表示列数の指定（ここでは50列を指定）
pd.set_option('display.max_rows', 50)
print(df2)
df2 = df2["ID"].unique()
print(str("通過人数は")+str(len(df2))+str("人です"))

       frame   ID        x       y      w      h
126      399    2  1106.67  909.33  32.82  64.35
127      400    2  1107.63  906.85  33.48  65.65
128      401    2  1108.47  905.08  33.60  66.14
129      402    2  1110.30  903.15  34.09  67.19
130      403    2  1110.92  900.72  34.36  68.45
...      ...  ...      ...     ...    ...    ...
86578  12701  402  1104.33  907.97  36.09  56.06
86593  12702  402  1105.04  906.22  36.44  56.42
86609  12703  402  1105.44  904.30  37.14  57.46
86625  12704  402  1107.48  902.33  35.33  54.29
86641  12705  402  1111.34  900.34  31.09  46.67

[635 rows x 6 columns]
通過人数は120人です


In [ ]:

im =cv2.imread("thumbnails/Jingubashi.png")
plt.imshow(im)

# 練習

In [15]:
text = "texts/1012_study.txt"
df = parser_byte(text)
#df = centerize(df)
df

frame   ID        x        y      w      h
0          1    1  1218.38   725.36  32.39  54.36
1          2    1  1217.92   725.66  32.23  53.96
2          3    1  1217.80   728.32  31.11  51.80
3          4    1  1217.19   729.12  30.92  51.16
4          5    1  1217.17   730.31  30.56  50.02
...      ...  ...      ...      ...    ...    ...
87226  12743  403  1172.01   934.92  30.56  54.96
87227  12743  404  1203.36   945.44  43.58  68.10
87228  12743  405  1204.67  1020.77  30.50  55.69
87229  12743  406  1274.44  1029.32  36.77  61.23
87230  12743  407  1240.11  1031.58  33.43  68.43

[87231 rows x 6 columns]

In [36]:
#%cd ./Trajectory_local_obara
import argparse
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from PIL import Image
import seaborn as sns

from utils.parser import *
from utils.homography import *

p_original = point_to_list(775,156, 1391,275 ,1398, 991 ,544, 590)
p_trans = point_to_list(1082,890, 677,744, 808,235, 1153,441)

M = homography_trans(p_original,p_trans)
print(M)

df['x_c'] = df['x'] + df['w']/2
df['y_c'] = df['y'] + df['h']/2
df2 = df.drop(columns=["frame", "ID", "x", "y", "w","h"])
i = 0
x_homo_list = []
y_homo_list = []
for index, row in df2.iterrows():
   x_c,y_c = (row['x_c'],row['y_c'])
   P = [x_c,y_c,1]
   t_p = np.dot(M,P)
   w= t_p[2]
   x_homo,y_homo = [t_p[0]/w,t_p[1]/w]
   x_homo_list.append(x_homo)
   y_homo_list.append(y_homo)

df['x_trans'] = x_homo_list
df['y_trans'] = y_homo_list

print(df)


[[-8.94467978e-01  1.35855203e+00  1.72875402e+03]
 [-2.35690028e-02 -5.75754723e-01  1.13419569e+03]
 [-8.13154018e-05  1.38432206e-03  1.00000000e+00]]
       frame   ID        x        y      w      h       x_c       y_c  \
0          1    1  1218.38   725.36  32.39  54.36  1234.575   752.540   
1          2    1  1217.92   725.66  32.23  53.96  1234.035   752.640   
2          3    1  1217.80   728.32  31.11  51.80  1233.355   754.220   
3          4    1  1217.19   729.12  30.92  51.16  1232.650   754.700   
4          5    1  1217.17   730.31  30.56  50.02  1232.450   755.320   
...      ...  ...      ...      ...    ...    ...       ...       ...   
87226  12743  403  1172.01   934.92  30.56  54.96  1187.290   962.400   
87227  12743  404  1203.36   945.44  43.58  68.10  1225.150   979.490   
87228  12743  405  1204.67  1020.77  30.50  55.69  1219.920  1048.615   
87229  12743  406  1274.44  1029.32  36.77  61.23  1292.825  1059.935   
87230  12743  407  1240.11  1031.58  33.43 

ValueError: shapes (3,3) and (87231,2) not aligned: 3 (dim 1) != 87231 (dim 0)